### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lukakralik** [Solirs/CDSC#1]
# TODO

## Common data structures
- [x] Doubly-linked list
- [x] Linked list
- [x] Queue
- [x] Deque 
- [x] Stack
- [x] Hash table
- [x] Heap
- [x] Tree 
- [x] Graph
- [x] Binary Tree

## Less known ones
- [x] Bloom filter
- [ ] Trie
- [ ] Skip list
- [ ] Rope
- [ ] Intrusive LL/DLL

## Tasks
- [x] Implement iterative tree traversal algorithms
- [x] Quicksort for lists
- [ ] Improve comments 

## Documentation
- [ ] Doubly-linked list
- [ ] Linked list
- [ ] Queue
- [ ] Deque 
- [ ] Stack
- [ ] Hash table
- [ ] Heap
- [ ] Tree 
- [ ] Binary Tree

# FIXES
